
services:
  storage_tools_device:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CONFIG_PORT: ${CONFIG_PORT}
    image: storage_tools_device
    container_name: storage_tools_device
    network_mode: host
    environment:
      - CONFIG_PORT=${CONFIG_PORT}
      - DATA_DIR=${DATA_DIR}
    volumes:
      - ${DATA_DIR}:${DATA_DIR}
      - ./config:/app/config
    tty: true
    stdin_open: true
    restart: always
