### Per device confing


###############################################################################
#                   Change to localize for your project 
###############################################################################

# Name of the overarching project.  
# Uncomment this line to always assoicate this device with a specific project. 
# project: "my_project_name"

# name of the platform  
robot_name: "my_robot_name"

# API key to log into the server
API_KEY_TOKEN: cbea87b419c09982

# which directories to watch for files to upload
watch:
  - /mnt/data/project


# Timezone used when converting UTC to local time
local_tz: "America/New_York"

# IP address and ports of all known servers
# The Device will by default use ZeroConf to find the nearest server.
# The Device will check these hosts for if ZeroConf fails to find a server. 

# servers:
#   - "127.0.0.1:8091"


###############################################################################
# Operational configurations
###############################################################################


# How many parallel threads for uploads
threads: 4

# What kinds of files to search for.  
# Comment out types to avoid.  
include_suffix:
  - mcap
  - mp4 
  - png 
  - txt
  - bag 
  - ass
  - yaml

# How many seconds to wait before checking servers again
wait_s: 5